# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(213, 342)
        Form.setMinimumSize(QtCore.QSize(170, 265))
        Form.setMaximumSize(QtCore.QSize(5555, 5555))
        Form.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/ico/engine.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.audio_lb = QtWidgets.QLabel(Form)
        self.audio_lb.setObjectName("audio_lb")
        self.verticalLayout_2.addWidget(self.audio_lb)
        self.music_per_lb = QtWidgets.QLabel(Form)
        self.music_per_lb.setObjectName("music_per_lb")
        self.verticalLayout_2.addWidget(self.music_per_lb)
        self.music_slider = QtWidgets.QSlider(Form)
        self.music_slider.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.music_slider.setMaximum(100)
        self.music_slider.setSingleStep(20)
        self.music_slider.setPageStep(10)
        self.music_slider.setProperty("value", 100)
        self.music_slider.setOrientation(QtCore.Qt.Horizontal)
        self.music_slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.music_slider.setTickInterval(20)
        self.music_slider.setObjectName("music_slider")
        self.verticalLayout_2.addWidget(self.music_slider)
        self.sounds_per_lb = QtWidgets.QLabel(Form)
        self.sounds_per_lb.setObjectName("sounds_per_lb")
        self.verticalLayout_2.addWidget(self.sounds_per_lb)
        self.sounds_slider = QtWidgets.QSlider(Form)
        self.sounds_slider.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.sounds_slider.setMaximum(100)
        self.sounds_slider.setSingleStep(20)
        self.sounds_slider.setPageStep(10)
        self.sounds_slider.setProperty("value", 100)
        self.sounds_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sounds_slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sounds_slider.setTickInterval(20)
        self.sounds_slider.setObjectName("sounds_slider")
        self.verticalLayout_2.addWidget(self.sounds_slider)
        self.gridLayout.addLayout(self.verticalLayout_2, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.difficulty_lb = QtWidgets.QLabel(Form)
        self.difficulty_lb.setObjectName("difficulty_lb")
        self.verticalLayout.addWidget(self.difficulty_lb)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.difficulty_spb = QtWidgets.QSpinBox(Form)
        self.difficulty_spb.setSuffix("")
        self.difficulty_spb.setMinimum(1)
        self.difficulty_spb.setMaximum(3)
        self.difficulty_spb.setObjectName("difficulty_spb")
        self.horizontalLayout.addWidget(self.difficulty_spb)
        self.difficulty_show_lb = QtWidgets.QLabel(Form)
        self.difficulty_show_lb.setObjectName("difficulty_show_lb")
        self.horizontalLayout.addWidget(self.difficulty_show_lb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 6, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 8, 0, 1, 1)
        self.logo = QtWidgets.QLabel(Form)
        self.logo.setTextFormat(QtCore.Qt.AutoText)
        self.logo.setObjectName("logo")
        self.gridLayout.addWidget(self.logo, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ok_btn = QtWidgets.QPushButton(Form)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout_2.addWidget(self.ok_btn)
        self.apply_btn = QtWidgets.QPushButton(Form)
        self.apply_btn.setObjectName("apply_btn")
        self.horizontalLayout_2.addWidget(self.apply_btn)
        self.cancel_btn = QtWidgets.QPushButton(Form)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 9, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Settings"))
        self.audio_lb.setText(_translate("Form", "<html><head/><body><p align=\"center\">Audio</p></body></html>"))
        self.music_per_lb.setText(_translate("Form", "Music: 100%"))
        self.sounds_per_lb.setText(_translate("Form", "Sounds: 100%"))
        self.difficulty_lb.setText(_translate("Form", "<html><head/><body><p align=\"center\">Difficulty</p></body></html>"))
        self.difficulty_show_lb.setText(_translate("Form", "<html><head/><body><p>Normal</p></body></html>"))
        self.logo.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Times New Roman\'; font-size:16pt; font-style:italic;\">SETTINGS</span></p></body></html>"))
        self.ok_btn.setText(_translate("Form", "OK"))
        self.apply_btn.setText(_translate("Form", "Apply"))
        self.cancel_btn.setText(_translate("Form", "Cancel"))


