# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trade.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(862, 443)
        Form.setMinimumSize(QtCore.QSize(862, 433))
        Form.setMaximumSize(QtCore.QSize(862, 443))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/ico/engine.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.hero_table = QtWidgets.QTableWidget(Form)
        self.hero_table.setGeometry(QtCore.QRect(0, 30, 321, 411))
        self.hero_table.setTabletTracking(False)
        self.hero_table.setAcceptDrops(False)
        self.hero_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.hero_table.setTabKeyNavigation(True)
        self.hero_table.setProperty("showDropIndicator", True)
        self.hero_table.setDragEnabled(True)
        self.hero_table.setDragDropOverwriteMode(False)
        self.hero_table.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.hero_table.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.hero_table.setAlternatingRowColors(False)
        self.hero_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.hero_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.hero_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.hero_table.setObjectName("hero_table")
        self.hero_table.setColumnCount(3)
        self.hero_table.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hero_table.setItem(2, 2, item)
        self.hero_table.verticalHeader().setVisible(False)
        self.trader_table = QtWidgets.QTableWidget(Form)
        self.trader_table.setGeometry(QtCore.QRect(540, 30, 321, 411))
        self.trader_table.setAcceptDrops(False)
        self.trader_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.trader_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.trader_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.trader_table.setTabKeyNavigation(True)
        self.trader_table.setProperty("showDropIndicator", True)
        self.trader_table.setDragEnabled(True)
        self.trader_table.setDragDropOverwriteMode(False)
        self.trader_table.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.trader_table.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.trader_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.trader_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.trader_table.setTextElideMode(QtCore.Qt.ElideRight)
        self.trader_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.trader_table.setShowGrid(True)
        self.trader_table.setGridStyle(QtCore.Qt.SolidLine)
        self.trader_table.setWordWrap(True)
        self.trader_table.setCornerButtonEnabled(True)
        self.trader_table.setRowCount(3)
        self.trader_table.setColumnCount(3)
        self.trader_table.setObjectName("trader_table")
        item = QtWidgets.QTableWidgetItem()
        self.trader_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trader_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.trader_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trader_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.trader_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.trader_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trader_table.setItem(2, 1, item)
        self.trader_table.verticalHeader().setHighlightSections(True)
        self.trader_name_lb = QtWidgets.QLabel(Form)
        self.trader_name_lb.setGeometry(QtCore.QRect(650, 0, 201, 31))
        self.trader_name_lb.setObjectName("trader_name_lb")
        self.done_btn = QtWidgets.QPushButton(Form)
        self.done_btn.setGeometry(QtCore.QRect(340, 410, 181, 23))
        self.done_btn.setObjectName("done_btn")
        self.hero_name_lb = QtWidgets.QLabel(Form)
        self.hero_name_lb.setGeometry(QtCore.QRect(10, 0, 201, 31))
        self.hero_name_lb.setObjectName("hero_name_lb")
        self.trader_money_lb = QtWidgets.QLabel(Form)
        self.trader_money_lb.setGeometry(QtCore.QRect(550, 0, 101, 31))
        self.trader_money_lb.setObjectName("trader_money_lb")
        self.hero_money_lb = QtWidgets.QLabel(Form)
        self.hero_money_lb.setGeometry(QtCore.QRect(210, 0, 101, 31))
        self.hero_money_lb.setObjectName("hero_money_lb")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(320, 160, 221, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.trade_action_lb = QtWidgets.QLabel(self.layoutWidget)
        self.trade_action_lb.setObjectName("trade_action_lb")
        self.verticalLayout.addWidget(self.trade_action_lb)
        self.item_lb = QtWidgets.QLabel(self.layoutWidget)
        self.item_lb.setObjectName("item_lb")
        self.verticalLayout.addWidget(self.item_lb)
        self.profit_lb = QtWidgets.QLabel(self.layoutWidget)
        self.profit_lb.setObjectName("profit_lb")
        self.verticalLayout.addWidget(self.profit_lb)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.ok_trade_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.ok_trade_btn.setObjectName("ok_trade_btn")
        self.horizontalLayout.addWidget(self.ok_trade_btn)
        self.cancel_trade_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.cancel_trade_btn.setObjectName("cancel_trade_btn")
        self.horizontalLayout.addWidget(self.cancel_trade_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Trade with Mr. Hankey"))
        item = self.hero_table.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.hero_table.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.hero_table.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.hero_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "na"))
        item = self.hero_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "ra"))
        item = self.hero_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "da"))
        __sortingEnabled = self.hero_table.isSortingEnabled()
        self.hero_table.setSortingEnabled(False)
        item = self.hero_table.item(0, 0)
        item.setText(_translate("Form", "a"))
        item = self.hero_table.item(0, 1)
        item.setText(_translate("Form", "ra1"))
        item = self.hero_table.item(0, 2)
        item.setText(_translate("Form", "da1"))
        item = self.hero_table.item(1, 0)
        item.setText(_translate("Form", "b"))
        item = self.hero_table.item(1, 1)
        item.setText(_translate("Form", "ra2"))
        item = self.hero_table.item(1, 2)
        item.setText(_translate("Form", "da2"))
        item = self.hero_table.item(2, 0)
        item.setText(_translate("Form", "Mace of Restoration"))
        item = self.hero_table.item(2, 1)
        item.setText(_translate("Form", "33-42 (x3)"))
        item = self.hero_table.item(2, 2)
        item.setText(_translate("Form", "4"))
        self.hero_table.setSortingEnabled(__sortingEnabled)
        self.trader_table.setSortingEnabled(False)
        __sortingEnabled = self.trader_table.isSortingEnabled()
        self.trader_table.setSortingEnabled(False)
        item = self.trader_table.item(0, 0)
        item.setText(_translate("Form", "a"))
        item = self.trader_table.item(0, 1)
        item.setText(_translate("Form", "f"))
        item = self.trader_table.item(1, 0)
        item.setText(_translate("Form", "b"))
        item = self.trader_table.item(1, 1)
        item.setText(_translate("Form", "agd"))
        item = self.trader_table.item(1, 2)
        item.setText(_translate("Form", "f"))
        item = self.trader_table.item(2, 0)
        item.setText(_translate("Form", "c"))
        item = self.trader_table.item(2, 1)
        item.setText(_translate("Form", "45"))
        self.trader_table.setSortingEnabled(__sortingEnabled)
        self.trader_name_lb.setText(_translate("Form", "<html><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Mr. Hankey</span></p></body></html>"))
        self.done_btn.setText(_translate("Form", "Done"))
        self.hero_name_lb.setText(_translate("Form", "<html><body><p><span style=\" font-size:11pt; font-weight:600;\">You</span></p></body></html>"))
        self.trader_money_lb.setText(_translate("Form", "<html><body><p><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:600;\">₪: 250</span></p></body></html>"))
        self.hero_money_lb.setText(_translate("Form", "<html><body><p align=\"right\"><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:600;\">₪: 17</span></p></body></html>"))
        self.trade_action_lb.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">-</span></p></body></html>"))
        self.item_lb.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Choose item</span></p></body></html>"))
        self.profit_lb.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">0 ₪</span></p></body></html>"))
        self.ok_trade_btn.setText(_translate("Form", "Trade"))
        self.cancel_trade_btn.setText(_translate("Form", "Clear"))


